import type { Article } from "@/content/types";

/**
 * How-to, rewritten on the URL first published 2026-08-19 (old text deleted
 * 2026-09-29, not restored). First-person facts are Palak's own (chat,
 * 2026-10-02): used ChatGPT's and Gemini's image generators for logos, icons and
 * cover art; 3 to 5 tries and 5 to 10 minutes for one usable image; text inside
 * images came out wrong; the style changed on every generation, which is the
 * reason ToolNest's covers are generated by the site instead of by an image
 * model. Gemini's stated capabilities, including its "better text rendering"
 * claim, the 1K and 2K download tiers and the daily quota, are from Google's
 * Gemini image help page read on 2026-10-02. The site's own cover art is
 * `src/lib/cover-art.ts`: 8 palettes and 6 motifs, hashed from the slug.
 */
export const howToChooseAnAiImageGenerator: Article = {
  slug: "how-to-choose-an-ai-image-generator",
  title: "Why This Site's Covers Are Not AI Images",
  excerpt:
    "One usable image took me 3 to 5 tries. The style never repeated, so a set of matching covers was not something I could get out of a prompt.",
  category: "ai-for-professionals",
  author: "palak-patel",
  tags: ["Image Generation", "Gemini", "ChatGPT", "DALL-E", "Design"],
  publishedAt: "2026-08-19",
  contentUpdatedAt: "2026-08-26",
  seoTitle: "AI Image Generators: Why I Stopped Using Them",
  seoDescription:
    "One usable image took 3 to 5 tries and 5 to 10 minutes. Text came out misspelt and the style never repeated, so this site generates its own covers.",
  pros: [
    "For a one-off image with no text in it, 5 to 10 minutes is quicker than briefing anyone",
    "Gemini downloads at 1K without a paid plan, 2K with one",
    "Trying a direction costs nothing, so you can reject four ideas cheaply",
  ],
  cons: [
    "Text inside the image came out misspelt every time I asked for it",
    "The style changed on every generation, so a matching set was not possible",
    "3 to 5 tries for one usable image, at 5 to 10 minutes a time",
    "Gemini has a daily image quota, and its best model needs a paid subscription",
  ],
  content: `
<p>I used two image generators on my own work, ChatGPT's and Gemini's, for logos, icons and cover art. One usable image took me 3 to 5 tries and 5 to 10 minutes. Two things went wrong every time. Any text I asked for inside the image came out misspelt. And the style changed with every generation, so I could not produce a set of covers that looked like they belonged together. That is why ToolNest generates its own covers instead.</p>

<p>The test I ran was never "is this image good". It was "can I get the second one to match the first", and the answer was no.</p>

<h2>The test that actually decides it</h2>
<p>If you are choosing an image generator, do not judge it on one image. One image always looks fine. Run this instead.</p>
<ol>
<li>Generate one image you are happy with, and keep the prompt exactly as you wrote it.</li>
<li>Change one small thing in the subject and nothing in the style words. A different object, a different label, the same look.</li>
<li>Put the two side by side and ask whether they could sit next to each other on a page.</li>
<li>Repeat twice more. You now have four images that were meant to be a set.</li>
<li>If they are not a set, stop. No amount of prompt editing will fix it, and I spent 3 to 5 tries per image finding that out.</li>
</ol>
<p>For me they were never a set. Line weights moved, the lighting changed, a style I had not asked for arrived in image three. Each one on its own was fine. Together they looked like four different people had made them, which is exactly the problem when the job is covers for one publication.</p>

<h2>Text inside an image is the other wall</h2>
<p>This one is worth knowing because the vendor page says otherwise.</p>
<p>Google's Gemini image help, read on 2 October 2026, lists under its features: "Better text rendering: Add text to images with more accurate spelling, for all supported languages." In my own use, every image I asked to contain words came back with the words wrong, and badly wrong: letters missing, letters invented, a word spelt two different ways in the same picture.</p>
<p>"More accurate" is doing a lot of work in that sentence, and it is probably true compared with where these models started. It still falls short of "the text will be right", and if you are making a logo or an icon with a name in it, right is the only threshold that counts. I stopped asking for text in images and put the words on top myself afterwards.</p>
<p>Two other limits from the same page, if you are planning around the free tier: downloads are 1K without a Google AI plan and 2K with one, there is a daily image quota, and the highest quality model needs a paid subscription. Image generation is 13 and over, editing is 18 and over.</p>

<h2>What this site does instead</h2>
<p>ToolNest's article covers are generated by the site, not by a model. The code picks from 8 colour palettes and 6 motifs, and it picks by hashing the article's slug. The same slug always produces the same cover, and no two palettes drift apart because none of it is being invented each time.</p>
<p>It is plainer than anything a model would give me. It also solves the problem I actually had: every cover on the site belongs to the same family, and I never spend 5 to 10 minutes on one. Pages do not even show the cover; it is there for the link preview when someone shares an article.</p>
<p>I went through the same reversal with video in <a href="/articles/ai-video-tools-worth-the-subscription">CapCut and Canva</a>. The generator handled one thing well. My job was making many things that match, which asks something else of it.</p>

<h2>So when is a generator the right choice</h2>
<p>When you need one image, it contains no text, and nothing has to match it later. A single illustration for a single post, a background, a placeholder you will replace. At 5 to 10 minutes it beats searching stock libraries, and rejecting four directions costs you nothing.</p>
<p>When you need a set, or a logo, or anything with a word in it, decide that before you start generating. I did not, and the 3 to 5 tries per image were how I found out.</p>
`,
  humanReview: {
    reviewedAt: "2026-10-02",
    experience:
      "I used two image generators on my own work, ChatGPT's and Gemini's, for logos, icons and cover art. One usable image took me 3 to 5 tries and 5 to 10 minutes. Two things went wrong every time. Any text I asked for inside the image came out misspelt. And the style changed with every generation, so I could not produce a set of covers that looked like they belonged together. That is why ToolNest generates its own covers instead.",
  },
  sources: [
    {
      title: "Create images with Gemini Apps",
      publisher: "Google",
      url: "https://support.google.com/gemini/answer/14286560",
      checkedAt: "2026-10-02",
    },
  ],
};
